<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ukrkms\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ukrkms/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0ukrkms.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0ukrkms\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0ukrkms\appDevDebugProjectContainer([
    'container.build_hash' => '0ukrkms',
    'container.build_id' => 'b0969446',
    'container.build_time' => 1616958367,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ukrkms');
